timezone: "Europe/Kyiv"
shops:
  - id: "silpo"
    default_cron: "0 1 * * 1"
  - id: "fora"
    default_cron: "0 1 * * 1"
  - id: "atb"
    default_cron: "22 1 * * 3"
categories:
  - name: "sparkling_drinks"
    words_to_ignore:
      - "cola"
    differentiation:
      - ["зб"]
      - ["пет"]
      - ["zero", "цукру"]
      - ["black"]
    jobs:
      - id: "sparkling_fora"
        shop_id: "fora"
        urls:
          - "https://fora.ua/category/solodka-voda-2483"
      - id: "sparkling_atb"
        shop_id: "atb"
        urls:
          - "https://www.atbmarket.com/catalog/307-napoi"
      - id: "sparkling_silpo"
        shop_id: "silpo"
        urls:
          - "https://silpo.ua/category/solodka-voda-gazovana-5095"
  - name: "chips"
    words_to_ignore: []
    differentiation: []
    jobs:
      - id: "chips_atb"
        shop_id: "atb"
        urls:
          - "https://www.atbmarket.com/catalog/cipsi"
      - id: "chips_fora"
        shop_id: "fora"
        urls:
          - "https://fora.ua/category/chypsy-2735"
      - id: "chips_silpo"
        shop_id: "silpo"
        urls:
          - "https://silpo.ua/category/chypsy-5017"
